# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Touris' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Touris
  pod "Gemini"

  target 'TourisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TourisUITests' do
    # Pods for testing
  end

end
